# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# This role will prepare target VMs with the right kernel and other system settings. This should only be run on ubuntu targets.
# In deploy mode it will patch the system with the right kernel.
# In clean mode it will do nothing atm.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
