# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# Wipe transient databases. You should know what you are doing here.
# withViews: True or False. Says, if the views have to be recreated.

- include_tasks: db/recreateDb.yml
  vars:
    dbName: "{{ db.whisk.actions }}"
    forceRecreation: True
- include_tasks: db/recreateDb.yml
  vars:
    dbName: "{{ db.whisk.activations }}"
    forceRecreation: True
  when: db.whisk.activations != db.whisk.actions

- include_tasks: recreateViews.yml
  when: withViews == True
